CREATE TABLE IF NOT EXISTS sys_dict_type (
    id          BIGINT PRIMARY KEY AUTO_INCREMENT,
    dict_type   VARCHAR(100) NOT NULL,
    dict_name   VARCHAR(100) NOT NULL,
    sort_order  INT DEFAULT 0,
    status      TINYINT DEFAULT 1,
    system_flag TINYINT DEFAULT 0,
    remark      VARCHAR(500),
    created_at  DATETIME,
    updated_at  DATETIME,
    deleted_at  DATETIME
);

CREATE TABLE IF NOT EXISTS sys_dict_item (
    id          BIGINT PRIMARY KEY AUTO_INCREMENT,
    dict_type   VARCHAR(100) NOT NULL,
    dict_value  VARCHAR(100) NOT NULL,
    dict_label  VARCHAR(100) NOT NULL,
    sort_order  INT DEFAULT 0,
    tag_type    VARCHAR(30),
    status      TINYINT DEFAULT 1,
    system_flag TINYINT DEFAULT 0,
    remark      VARCHAR(500),
    created_at  DATETIME,
    updated_at  DATETIME,
    deleted_at  DATETIME
);

INSERT INTO sys_dict_type (dict_type, dict_name, sort_order, status, system_flag, created_at, updated_at) VALUES
('ROOM_TYPE', '房间类型', 10, 1, 1, NOW(), NOW()),
('ROOM_STATUS', '房间状态', 20, 1, 1, NOW(), NOW()),
('BED_STATUS', '床位状态', 30, 1, 1, NOW(), NOW()),
('BED_TYPE', '床位类型', 40, 1, 1, NOW(), NOW()),
('GENDER_LIMIT', '性别限制', 50, 1, 1, NOW(), NOW()),
('BUILDING_STATUS', '楼栋状态', 60, 1, 1, NOW(), NOW()),
('RESIDENT_TYPE', '居住人类型', 70, 1, 1, NOW(), NOW()),
('RESIDENT_STATUS', '居住人状态', 80, 1, 1, NOW(), NOW()),
('INTAKE_STATUS', '入住申请状态', 90, 1, 1, NOW(), NOW()),
('INTAKE_SOURCE', '入住来源', 100, 1, 1, NOW(), NOW()),
('CHECKOUT_STATUS', '退宿状态', 110, 1, 1, NOW(), NOW()),
('CHECKOUT_SOURCE', '退宿来源', 120, 1, 1, NOW(), NOW()),
('BILL_STATUS', '账单状态', 130, 1, 1, NOW(), NOW()),
('BILL_TYPE', '账单类型', 140, 1, 1, NOW(), NOW()),
('PAY_METHOD', '支付方式', 150, 1, 1, NOW(), NOW()),
('METER_TYPE', '抄表类型', 160, 1, 1, NOW(), NOW()),
('REPAIR_STATUS', '维修状态', 170, 1, 1, NOW(), NOW()),
('REPAIR_PRIORITY', '维修优先级', 180, 1, 1, NOW(), NOW()),
('ROOM_FACILITY', '房间设施', 190, 1, 1, NOW(), NOW());

INSERT INTO sys_dict_item (dict_type, dict_value, dict_label, sort_order, tag_type, status, system_flag, created_at, updated_at) VALUES
('ROOM_TYPE', '1', '单人间', 1, 'success', 1, 1, NOW(), NOW()),
('ROOM_TYPE', '2', '双人间', 2, 'primary', 1, 1, NOW(), NOW()),
('ROOM_TYPE', '3', '四人间', 3, 'warning', 1, 1, NOW(), NOW()),
('ROOM_STATUS', '1', '空闲', 1, 'success', 1, 1, NOW(), NOW()),
('ROOM_STATUS', '2', '已满', 2, 'danger', 1, 1, NOW(), NOW()),
('ROOM_STATUS', '3', '维修中', 3, 'warning', 1, 1, NOW(), NOW()),
('BED_STATUS', '1', '空闲', 1, 'success', 1, 1, NOW(), NOW()),
('BED_STATUS', '2', '已入住', 2, 'primary', 1, 1, NOW(), NOW()),
('BED_STATUS', '3', '维修中', 3, 'warning', 1, 1, NOW(), NOW()),
('BED_TYPE', '1', '上铺', 1, 'info', 1, 1, NOW(), NOW()),
('BED_TYPE', '2', '下铺', 2, 'info', 1, 1, NOW(), NOW()),
('BED_TYPE', '3', '独立床', 3, 'success', 1, 1, NOW(), NOW()),
('GENDER_LIMIT', '0', '不限', 0, 'info', 1, 1, NOW(), NOW()),
('GENDER_LIMIT', '1', '男', 1, 'primary', 1, 1, NOW(), NOW()),
('GENDER_LIMIT', '2', '女', 2, 'danger', 1, 1, NOW(), NOW()),
('BUILDING_STATUS', '1', '启用', 1, 'success', 1, 1, NOW(), NOW()),
('BUILDING_STATUS', '0', '停用', 2, 'info', 1, 1, NOW(), NOW()),
('RESIDENT_TYPE', '1', '员工', 1, 'primary', 1, 1, NOW(), NOW()),
('RESIDENT_TYPE', '2', '外包', 2, 'warning', 1, 1, NOW(), NOW()),
('RESIDENT_STATUS', '1', '在住', 1, 'success', 1, 1, NOW(), NOW()),
('RESIDENT_STATUS', '2', '退宿', 2, 'info', 1, 1, NOW(), NOW()),
('INTAKE_STATUS', '1', '待分配', 1, 'warning', 1, 1, NOW(), NOW()),
('INTAKE_STATUS', '2', '已入住', 2, 'success', 1, 1, NOW(), NOW()),
('INTAKE_STATUS', '3', '已取消', 3, 'info', 1, 1, NOW(), NOW()),
('INTAKE_SOURCE', '1', '手工录入', 1, 'primary', 1, 1, NOW(), NOW()),
('INTAKE_SOURCE', '2', 'Excel导入', 2, 'success', 1, 1, NOW(), NOW()),
('INTAKE_SOURCE', '3', 'OA同步', 3, 'warning', 1, 1, NOW(), NOW()),
('CHECKOUT_STATUS', '1', '待确认', 1, 'warning', 1, 1, NOW(), NOW()),
('CHECKOUT_STATUS', '2', '已退宿', 2, 'success', 1, 1, NOW(), NOW()),
('CHECKOUT_STATUS', '3', '已取消', 3, 'info', 1, 1, NOW(), NOW()),
('CHECKOUT_SOURCE', '1', '手工录入', 1, 'primary', 1, 1, NOW(), NOW()),
('CHECKOUT_SOURCE', '2', 'Excel导入', 2, 'success', 1, 1, NOW(), NOW()),
('CHECKOUT_SOURCE', '3', 'OA同步', 3, 'warning', 1, 1, NOW(), NOW()),
('BILL_STATUS', '1', '未支付', 1, 'warning', 1, 1, NOW(), NOW()),
('BILL_STATUS', '2', '已支付', 2, 'success', 1, 1, NOW(), NOW()),
('BILL_STATUS', '3', '已作废', 3, 'info', 1, 1, NOW(), NOW()),
('BILL_TYPE', '1', '住宿费', 1, 'primary', 1, 1, NOW(), NOW()),
('BILL_TYPE', '2', '水电费', 2, 'success', 1, 1, NOW(), NOW()),
('PAY_METHOD', '1', '现金', 1, 'info', 1, 1, NOW(), NOW()),
('PAY_METHOD', '2', '转账', 2, 'primary', 1, 1, NOW(), NOW()),
('PAY_METHOD', '3', '代扣', 3, 'success', 1, 1, NOW(), NOW()),
('METER_TYPE', '1', '电表', 1, 'warning', 1, 1, NOW(), NOW()),
('METER_TYPE', '2', '水表', 2, 'primary', 1, 1, NOW(), NOW()),
('REPAIR_STATUS', '1', '待受理', 1, 'warning', 1, 1, NOW(), NOW()),
('REPAIR_STATUS', '2', '处理中', 2, 'primary', 1, 1, NOW(), NOW()),
('REPAIR_STATUS', '3', '已完成', 3, 'success', 1, 1, NOW(), NOW()),
('REPAIR_PRIORITY', '1', '普通', 1, 'info', 1, 1, NOW(), NOW()),
('REPAIR_PRIORITY', '2', '紧急', 2, 'danger', 1, 1, NOW(), NOW()),
('ROOM_FACILITY', '空调', '空调', 1, 'primary', 1, 1, NOW(), NOW()),
('ROOM_FACILITY', '热水器', '热水器', 2, 'success', 1, 1, NOW(), NOW()),
('ROOM_FACILITY', '衣柜', '衣柜', 3, 'warning', 1, 1, NOW(), NOW()),
('ROOM_FACILITY', '书桌', '书桌', 4, 'info', 1, 1, NOW(), NOW());
